template:
  id: "bmad.pm.product-strategy.v1"
  name: "Product Manager — Product Strategy"
sections:
  - id: "vision"
    title: "Product Vision"
    description: "Long-term product vision. Example: 'Vision: Become the AI-native productivity platform that helps knowledge workers achieve 10x more. Empower individuals and teams with intelligent task management.'"
  - id: "market_positioning"
    title: "Market Positioning"
    description: "How product is positioned. Example: 'Positioning: AI-first task management for modern teams. More intelligent than Todoist, simpler than Asana, more affordable than enterprise tools.'"
  - id: "target_segments"
    title: "Target Segments"
    description: "Who we're building for. Example: 'Primary: Knowledge workers at tech companies (50-500 employees). Secondary: Freelancers and consultants. Future: Enterprise teams (500+).'"
  - id: "differentiation"
    title: "Differentiation Strategy"
    description: "What makes us unique. Example: 'Differentiation: AI-powered prioritization and insights. Simple, intuitive UI. Affordable pricing. Fast time to value. No heavy onboarding required.'"
  - id: "business_model"
    title: "Business Model"
    description: "How we make money. Example: 'Model: Freemium SaaS. Free: 5 users, basic features. Pro: $10/user/mo, AI features. Team: $15/user/mo, collaboration. Enterprise: custom pricing, SSO, support.'"
  - id: "growth_strategy"
    title: "Growth Strategy"
    description: "How we'll grow. Example: 'Strategy: Product-led growth. Viral free tier → paid conversion. Bottom-up adoption in companies. Content marketing. Integration partnerships. Community building.'"
  - id: "competitive_advantage"
    title: "Competitive Advantage"
    description: "Sustainable advantages. Example: 'Advantages: 1. AI expertise and data, 2. Developer velocity, 3. User-centric culture, 4. Strong retention (90% annual), 5. Network effects from integrations.'"
  - id: "strategic_priorities"
    title: "Strategic Priorities"
    description: "Top priorities for next 12 months. Example: '1. Build AI moat (prioritization, insights), 2. Launch mobile for market expansion, 3. Enterprise features for upmarket, 4. Integration ecosystem for stickiness.'"
  - id: "success_metrics"
    title: "Strategic Success Metrics"
    description: "Long-term KPIs. Example: 'North Star: Weekly active users. Supporting: Activation rate, Retention (Day 7, Month 1), Revenue per user, Net revenue retention, NPS. Targets: 100K users, $10M ARR by end of year.'"
metadata:
  usage: "strategy"
  priority: "high"
  workflow: "strategic-planning"
